inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  SuggestExtensions: false
  Exclude:
    - "scratchpad/**/*"
    - "lib_rdoc/**/*"

# Common configuration.
plugins:
  - rubocop-rspec
  - rubocop-sequel
  - rubocop-performance
  - rubocop-rake
  - rubocop-sequel

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementLineBreak:
  Enabled: true
Style/SuperArguments: # new in 1.64
  Enabled: true
Style/SuperWithArgsParentheses: # new in 1.58
  Enabled: true
Style/SwapValues: # new in 1.1
  Enabled: true
Style/YAMLFileRead: # new in 1.53
  Enabled: true
