source "https://rubygems.org"

gemspec

group :development, :test do
  gem 'rdoc'
  gem "rspec", "~> 3.10"
  gem 'rubocop', require: false
  gem 'rubocop-minitest'
  gem 'rubocop-packaging'
  gem 'rubocop-performance'
  gem 'rubocop-rake'
  gem 'rubocop-rspec'
  gem 'rubocop-sequel'
  gem 'rubocop-shopify'
  gem 'rubocop-thread_safety'
  gem 'ruby-lsp'
  gem 'yard'
end

gem 'clipboard'
gem 'colorize'
gem 'dotenv'
gem 'dry-configurable'
gem 'dry-container'
gem 'erb'
gem 'front_matter_parser'
gem 'git'
gem 'pg'
gem 'pry-doc'
gem 'pry'
gem 'rbs'
gem 'ruby_llm-mcp'
gem 'ruby_llm-schema'
gem 'ruby_llm'
gem 'sequel'
gem 'solargraph'
gem 'terrapin'
gem 'tty-box'
gem 'tty-command'
gem 'tty-config'
gem 'tty-cursor'
gem 'tty-editor'
gem 'tty-file'
gem 'tty-link'
gem 'tty-logger'
gem 'tty-markdown'
gem 'tty-pager'
gem 'tty-progressbar'
gem 'tty-prompt'
gem 'tty-reader'
gem 'tty-screen'
gem 'tty-spinner'
gem 'tty-table'
gem 'tty-tree'
gem 'tty-which'
