# frozen_string_literal: true

module ComputerTools
  module Actions
    # Parses a raw JSON output file from Deepgram's transcription service and
    # converts it into a more human-readable format.
    #
    # This action serves as a comprehensive tool for processing Deepgram transcripts.
    # It not only converts the transcript into formats like Markdown, SRT, or a
    # simplified JSON, but also prints a high-level summary of the content
    # (word count, topics, etc.) to the console during the process.
    #
    # @example Basic usage to create a Markdown file
    #   action = ComputerTools::Actions::DeepgramParseAction.new(
    #     json_file: 'path/to/transcript.json',
    #     output_format: 'markdown'
    #   )
    #   action.call
    #   # => 📄 Output written to: path/to/transcript_analysis.md
    #
    # @example Outputting an SRT file to the console
    #   action = ComputerTools::Actions::DeepgramParseAction.new(
    #     json_file: 'path/to/meeting.json',
    #     output_format: 'srt',
    #     console_output: true
    #   )
    #   action.call
    class DeepgramParseAction < ComputerTools::Actions::BaseAction
      # Initializes the parsing action with necessary parameters.
      #
      # @param json_file [String] The path to the input Deepgram JSON file.
      # @param output_format [String] The desired output format. Supported formats
      #   are 'markdown' (or 'md'), 'srt', 'json', and 'summary'. Defaults to 'markdown'.
      # @param output_file [String, nil] The explicit path for the output file.
      #   If nil, a path is automatically generated based on the input file name
      #   and output format.
      # @param console_output [Boolean] If true, the result is printed to the
      #   console instead of being written to a file. Defaults to false.
      def initialize(json_file:, output_format: 'markdown', output_file: nil, console_output: false)
        @json_file = json_file
        @output_format = output_format.downcase
        @output_file = output_file
        @console_output = console_output
      end

      # Executes the parsing and formatting process.
      #
      # This method orchestrates the entire workflow:
      # 1. Parses the input JSON file.
      # 2. Displays a summary of the transcript's statistics.
      # 3. Formats the content into the specified output format.
      # 4. Writes the content to a file or prints it to the console.
      #
      # @return [Boolean] Returns `true` on successful completion, or `false` if
      #   an error occurs during the process.
      def call
        puts "🎙️  Parsing Deepgram output...".colorize(:blue)

        begin
          parser = ComputerTools::Wrappers::DeepgramParser.new(@json_file)
          formatter = ComputerTools::Wrappers::DeepgramFormatter.new(parser)

          # Display summary statistics
          display_summary(parser.summary_stats)

          # Generate output content
          content = generate_content(formatter)

          # Output the content
          handle_output(content)

          puts "✅ Parsing completed successfully!".colorize(:green)
          true
        rescue StandardError => e
          puts "❌ Error parsing Deepgram file: #{e.message}".colorize(:red)
          puts e.backtrace.first(3).join("\n") if ENV['DEBUG']
          false
        end
      end

      private

      # @private
      # Generates the output content based on the selected format.
      #
      # If an unknown format is provided, it logs a warning and defaults to Markdown.
      #
      # @param formatter [ComputerTools::Wrappers::DeepgramFormatter] The formatter
      #   instance containing the parsed data.
      # @return [String] The formatted content as a string.
      def generate_content(formatter)
        case @output_format
        when 'markdown', 'md'
          formatter.to_markdown
        when 'srt'
          formatter.to_srt
        when 'json'
          formatter.to_json
        when 'summary'
          formatter.to_summary
        else
          puts "⚠️  Unknown format '#{@output_format}', defaulting to markdown".colorize(:yellow)
          formatter.to_markdown
        end
      end

      # @private
      # Handles the final output, either by writing to a file or printing to the console.
      #
      # @param content [String] The formatted content to be output.
      # @return [void]
      def handle_output(content)
        if @console_output
          puts "\n" + ("=" * 60)
          puts content
        else
          output_file = determine_output_file
          File.write(output_file, content)
          puts "📄 Output written to: #{output_file}".colorize(:cyan)
        end
      end

      # @private
      # Determines the appropriate output file path.
      #
      # If an `@output_file` was specified during initialization, it is used.
      # Otherwise, a new filename is generated by taking the base name of the
      # input file and appending a format-specific suffix (e.g., `_analysis.md`, `.srt`).
      #
      # @return [String] The absolute or relative path for the output file.
      def determine_output_file
        return @output_file if @output_file

        base_name = File.basename(@json_file, ".*")
        extension = case @output_format
                    when 'srt'
                      '.srt'
                    when 'json'
                      '_parsed.json'
                    when 'summary'
                      '_summary.txt'
                    else
                      '_analysis.md'
                    end

        File.join(File.dirname(@json_file), "#{base_name}#{extension}")
      end

      # @private
      # Displays a formatted summary of the transcript's statistics to the console.
      #
      # @param stats [Hash] A hash containing summary data like word count,
      #   topics, intents, etc.
      # @return [void]
      def display_summary(stats)
        puts "\n📊 Content Overview:".colorize(:blue)
        puts "   • Total Words: #{stats[:total_words]}"
        puts "   • Total Sentences: #{stats[:total_sentences]}"
        puts "   • Total Paragraphs: #{stats[:total_paragraphs]}"
        puts "   • Topics Identified: #{stats[:total_topics]}"
        puts "   • Intents Detected: #{stats[:total_intents]}"
        puts "   • Transcript Length: #{stats[:transcript_length]} characters"
        puts ""
      end
    end
  end
end