#!/usr/bin/env ruby

lib_dir = File.expand_path(File.join(__dir__, "..", "lib"))
$:.unshift lib_dir unless $:.include?(lib_dir)

require "ComputerTools"

# Initialize the dependency injection container
ComputerTools.initialize_container

ComputerTools::CLI.start(ARGV)
